- id: primary-openstack-network-agents-l3
  type: skipped
- id: openstack-network-agents-l3
  type: skipped
- id: opflex-config
  type: puppet
  role: ['primary-controller','controller','compute']
  requires: [post_deployment_end]
  parameters:
    puppet_manifest: puppet/site.pp
    puppet_modules: puppet/modules/
    timeout: 3600
