attributes:
  metadata:
    restrictions:
      - condition: "not (cluster:net_provider == 'neutron' and networking_parameters:segmentation_type == 'vlan')"
        action: hide
  driver_type:
    type: "radio"
    weight: 33
    value: "ML2"
    label: "APIC Driver mode"
    restrictions:
      - condition: "not (cluster:net_provider == 'neutron' and networking_parameters:segmentation_type == 'vlan')"
        action: disable
    values:
      - data: "ML2"
        label: "ML2"
        description: "ML2 Driver"
      - data: "GBP"
        label: "Group Based Policy"
        description: "Group Based Policy Driver"
  apic_hosts:
    value: '10.0.0.100'
    label: 'APIC Host'
    description: 'Comma separated list of Cisco APIC IP addresses'
    weight: 41
    type: "text"
  apic_username:
    value: 'admin'
    label: 'APIC Username'
    description: 'Username for Cisco APIC; usually admin is used to allow configuration for multiple tenants'
    weight: 42
    type: "text"
    regex:
      source: '\S'
      error: "Error field cannot be empty"
  apic_password:
    value: 'password'
    label: 'APIC Password'
    description: 'Password for the Cisco APIC user identified by the username'
    weight: 43
    type: "password"
    regex:
      source: '\S'
      error: "Error field cannot be empty"
  opflex_encap_type:
    type: "radio"
    weight: 45
    label: "Opflex Encap mode, vlan or vxlan"
    value: 'vlan'
    values:
      - data: 'vlan'
        label: "VLAN"
        description: "VLAN encap"
      - data: 'vxlan'
        label: "VxLAN"
        description: "VxLAN encap"
  apic_system_id:
    type: "text"
    weight: 46
    value: "openstack1"
    label: "OpenStack system ID:"
    description: "OpenStack ID to be used by APIC"
  apic_infra_vlan:
    value: ''
    label: 'APIC Infra Vlan'
    description: 'Infrastructure vlan number for APIC'
    weight: 47
    type: "text"
    regex:
      source: '\d'
      error: "Error field cannot be empty, has to be numeric"
  apic_infra_subnet_gateway:
    value: '10.0.0.30'
    label: 'APIC Infra Subnet Gateway'
    description: 'APIC infra tenant, default BD subnet'
    weight: 48
    type: "text"
    regex:
      source: '^((?:\d|1?\d\d|2[0-4]\d|25[0-5])(?:\.(?:\d|1?\d\d|2[0-4]\d|25[0-5])){3})|(?:^)$'
      error: "Invalid IP address"
  apic_infra_anycast_address:
    value: '10.0.0.32'
    label: 'APIC Infra anycast address'
    description: 'APIC anycast address, default is 10.0.0.32'
    weight: 49
    type: "text"
    regex:
      source: '^((?:\d|1?\d\d|2[0-4]\d|25[0-5])(?:\.(?:\d|1?\d\d|2[0-4]\d|25[0-5])){3})|(?:^)$'
      error: "Invalid IP address"
    restrictions:
      - condition: "(settings:aci_opflex.opflex_encap_type.value == 'vlan')"
        action: hide
  static_config:
    type: "textarea"
    weight: 51
    value: ""
    label: "Static Topology"
    description: "Example:\napic_switch:201/compute11,compute21=1/10\napic_switch:201/compute12=1/11\n"
  apic_external_network:
    type: "text"
    weight: 59
    value: "my_ext_net"
    label: "APIC external network:"
    description: "External network name, which will be used by APIC"
    regex:
      source: '\S'
      error: "Error field cannot be empty"
  external_epg:
    type: "text"
    weight: 60
    value: "ext_epg"
    label: "APIC External EPG name:"
    description: "APIC external EPG name"
    regex:
      source: '\S'
      error: "Error field cannot be empty"
  snat_gateway_mask:
    type: "text"
    weight: 76
    value: '1.1.1.1/24'
    label: "SNAT gateway/mask:"
    description: "SNAT gateway and number of mask bits"
    regex:
      source: '^(?:(?:[0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}(?:[1-9]|[1-9][1-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\/([1-9]|[1-2]\d|3[0-2])$'
      error: "Invalid Gateway / Mask bits"
  additional_config:
    type: "textarea"
    weight: 79
    value: ""
    label: "Additional config"
    description: "Example:\nml2_cisco_apic/apic_vpc_pairs=201:202,203:204"
  edgenat:
    type: "checkbox"
    weight: 81
    value: false
    label: "EdgeNAT"
    description: "Enable Edge NAT"
  edgenat_vlan_range:
    type: "text"
    weight: 82
    value: ''
    label: "Edge NAT vlan range"
    description: "vlan range e.g. 2001:2020"
    regex:
      source: '\S'
      error: "Error field cannot be empty"
    restrictions:
      - condition: "(settings:aci_opflex.edgenat.value == false)"
        action: hide
  router_plugin:
    type: "checkbox"
    weight: 83
    value: false
    label: "Router plugin"
    description: "Enable router plugin"
    restrictions:
      - condition: "(settings:aci_opflex.edgenat.value == false)"
        action: hide
  router_mgmt_ip:
    type: "text"
    weight: 84
    value: '1.1.1.2'
    label: "Router IP address"
    regex:
      source: '^((?:\d|1?\d\d|2[0-4]\d|25[0-5])(?:\.(?:\d|1?\d\d|2[0-4]\d|25[0-5])){3})|(?:^)$'
      error: "Invalid IP address"
    restrictions:
      - condition: "(settings:aci_opflex.router_plugin.value == false)"
        action: hide
  router_user:
    type: "text"
    weight: 85
    value: 'admin'
    label: "Router User name"
    regex:
      source: '\S'
      error: "Error field cannot be empty"
    restrictions:
      - condition: "(settings:aci_opflex.router_plugin.value == false)"
        action: hide
  router_password:
    type: "password"
    weight: 86
    value: ''
    label: "Router User password"
    regex:
      source: '\S'
      error: "Error field cannot be empty"
    restrictions:
      - condition: "(settings:aci_opflex.router_plugin.value == false)"
        action: hide
  router_internal_interface:
    type: "text"
    weight: 87
    value: ''
    label: "Router internal interface"
    regex:
      source: '\S'
      error: "Error field cannot be empty"
    restrictions:
      - condition: "(settings:aci_opflex.router_plugin.value == false)"
        action: hide
  router_external_interface:
    type: "text"
    weight: 88
    value: ''
    label: "Router external interface"
    regex:
      source: '\S'
      error: "Error field cannot be empty"
    restrictions:
      - condition: "(settings:aci_opflex.router_plugin.value == false)"
        action: hide
  external_segments:
    type: "textarea"
    weight: 89
    value: ""
    label: "External segments config blob"
    restrictions:
      - condition: "(settings:aci_opflex.router_plugin.value == false)"
        action: hide
    
