#Class lldp::params

class lldp::params {

    $autoupdate = false
    $package_name = 'lldpd'
    $service_name = 'lldpd'

    case $::osfamily {
        'Debian': {
            $config_file_path = '/etc/default/lldpd'
            $config_file_data_vxlan = '#Generated by puppet <%= "\n" %>DAEMON_ARGS="-r -c -I eth*"<%= "\n" %>'
            $config_file_data_vlan = '#Generated by puppet <%= "\n" %>DAEMON_ARGS="-r -I eth*"<%= "\n" %>'
        }
        'RedHat': {
            $config_file_path = '/etc/sysconfig/lldpd'
            $config_file_data_vxlan = '#Generated by puppet <%= "\n" %>LLDPD_OPTIONS="-r -c -I eth*"<%= "\n" %>'
            $config_file_data_vlan = '#Generated by puppet <%= "\n" %>LLDPD_OPTIONS="-r -I eth*"<%= "\n" %>'
        }
        default: { fail("lldp: unsuported OS family ${::osfamily}") }
    }
}
